name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  go_router: ^14.4.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
